/**
 * ชื่อหัวข้อสำหรับแสดงผล — คีย์ตรงกับ Question.topic และ Course.topics
 * (สคริปต์ scripts/tag-question-topics.mjs เป็นตัวกำหนดว่ามีหัวข้ออะไรบ้าง)
 */
export const TOPIC_LABELS: Record<string, string> = {
  'verb-to-be': 'Verb to be',
  articles: 'Articles (a/an/the)',
  plurals: 'คำนามพหูพจน์',
  'pronouns-possessives': 'สรรพนามและความเป็นเจ้าของ',
  'present-simple': 'Present simple',
  'present-continuous': 'Present continuous',
  'past-simple': 'Past simple',
  'wh-questions': 'การตั้งคำถาม Wh-',
  prepositions: 'คำบุพบท',
  comparatives: 'การเปรียบเทียบ',
  quantifiers: 'การบอกปริมาณ',
  'modals-basic': 'Modal verbs พื้นฐาน',
  future: 'การพูดถึงอนาคต',
  'adjectives-adverbs': 'คำคุณศัพท์และคำวิเศษณ์',
  'present-perfect': 'Present perfect',
  'past-perfect': 'Past perfect',
  conditionals: 'ประโยคเงื่อนไข',
  passive: 'Passive voice',
  'reported-speech': 'การเล่าความ',
  'relative-clauses': 'Relative clauses',
  'gerund-infinitive': 'Gerund และ Infinitive',
  'modals-advanced': 'Modal verbs ขั้นสูง',
  'used-to': 'used to / be used to',
  inversion: 'Inversion',
  'phrasal-verbs': 'Phrasal verbs',
  collocations: 'คำที่ใช้คู่กัน',
  'linking-words': 'คำเชื่อมและการขัดแย้ง',
  subjunctive: 'Subjunctive',
  'participle-clauses': 'Participle clauses',
  idioms: 'สำนวน',
  'register-nuance': 'ระดับภาษาและนัยของคำ',
  'vocabulary-precision': 'การเลือกใช้คำ',
  'reading-detail': 'อ่านจับใจความ: รายละเอียด',
  'reading-main-idea': 'อ่านจับใจความ: ใจความหลัก',
  'reading-inference': 'อ่านจับใจความ: ตีความ',
  'word-order': 'ลำดับคำในประโยค',
  'word-formation': 'การสร้างคำ',

  // คณิตศาสตร์
  arithmetic: 'การบวก ลบ คูณ หาร',
  fractions: 'เศษส่วน',
  decimals: 'ทศนิยม',
  'units-measurement': 'หน่วยและการวัด',
  'data-reading': 'การอ่านตารางและแผนภูมิ',
  percentage: 'ร้อยละ',
  'ratio-proportion': 'อัตราส่วนและสัดส่วน',
  'rate-speed': 'อัตราเร็วและระยะทาง',
  'geometry-perimeter-area': 'พื้นที่และเส้นรอบรูป',
  'geometry-volume': 'ปริมาตร',
  'geometry-angles': 'มุมและรูปเรขาคณิต',
  'statistics-average': 'ค่าเฉลี่ยและค่ากลาง',
  'statistics-spread': 'การกระจายของข้อมูล',
  'linear-equations': 'สมการเชิงเส้น',
  'simultaneous-equations': 'ระบบสมการ',
  sequences: 'ลำดับ',
  series: 'อนุกรม',
  pythagoras: 'ทฤษฎีบทพีทาโกรัส',
  similarity: 'รูปคล้าย',
  'coordinate-geometry': 'เรขาคณิตวิเคราะห์',
  probability: 'ความน่าจะเป็น',
  functions: 'ฟังก์ชันและกราฟ',
  quadratics: 'สมการกำลังสอง',
  modelling: 'การสร้างแบบจำลอง',
  'exponential-growth': 'การเติบโตแบบทบต้น',
  trigonometry: 'ตรีโกณมิติ',
  logarithms: 'ลอการิทึม',
  'calculus-intro': 'แคลคูลัสเบื้องต้น',
  combinatorics: 'การเรียงสับเปลี่ยนและจัดหมู่',
  sets: 'เซต',
  'proof-logic': 'ตรรกะและการพิสูจน์',
  generalisation: 'การสรุปรูปทั่วไป',

  // วิทยาศาสตร์
  'living-things': 'สิ่งมีชีวิต',
  'plants-photosynthesis': 'พืชและการสังเคราะห์ด้วยแสง',
  'matter-states': 'สสารและสถานะ',
  'human-body': 'ร่างกายมนุษย์',
  'scientific-tools': 'เครื่องมือวิทยาศาสตร์',
  'scientific-method': 'วิธีการทางวิทยาศาสตร์',
  ecosystems: 'ระบบนิเวศ',
  'earth-atmosphere': 'บรรยากาศและวัฏจักรน้ำ',
  'forces-motion': 'แรงและการเคลื่อนที่',
  energy: 'พลังงาน',
  cells: 'เซลล์',
  'earth-space': 'โลกและอวกาศ',
  'electricity-magnetism': 'ไฟฟ้าและแม่เหล็ก',
  'chemical-reactions': 'ปฏิกิริยาเคมี',
  'chemistry-acids': 'กรดและเบส',
  'waves-sound-light': 'คลื่น เสียง และแสง',
  genetics: 'พันธุกรรม',
  evolution: 'วิวัฒนาการ',
  'data-analysis': 'การตีความข้อมูล',
  'nuclear-basics': 'กัมมันตภาพรังสี',
  'nature-of-science': 'ธรรมชาติของวิทยาศาสตร์',
  'environment-climate': 'สิ่งแวดล้อมและภูมิอากาศ',
}

/** หัวข้อที่ไม่รู้จักให้แสดงคีย์ดิบ ดีกว่าแสดงค่าว่าง */
export function topicLabel(topic: string): string {
  return TOPIC_LABELS[topic] ?? topic
}
